services:
  postgres:
    image: akshaygouda646/smartims-postgres:v1
    container_name: smartims-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_ims
      POSTGRES_USER: akshay_gouda
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - smartims-postgres-data:/var/lib/postgresql/data
    networks:
      - smartims-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akshay_gouda -d smart_ims"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: akshaygouda646/smartims-backend:v1
    container_name: smartims-backend
    restart: unless-stopped
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/smart_ims
      DB_USERNAME: akshay_gouda
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      FRONTEND_LOGIN_URL: http://localhost:5173/login
      MANAGEMENT_HEALTH_MAIL_ENABLED: "false"

    ports:
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - smartims-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8081
    image: smartims-frontend-local:v1
    container_name: smartims-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - smartims-network

  prometheus:
    image: akshaygouda646/smartims-prometheus:v1
    container_name: smartims-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9092:9090"
    depends_on:
      - backend
    networks:
      - smartims-network

  grafana:
    image: akshaygouda646/smartims-grafana:v1
    container_name: smartims-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - smartims-grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - smartims-network
  
  sonarqube:
    image: sonarqube:lts-community
    container_name: smartims-sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - smartims-sonarqube-data:/opt/sonarqube/data
      - smartims-sonarqube-logs:/opt/sonarqube/logs
      - smartims-sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - smartims-network


volumes:
  smartims-postgres-data:
  smartims-grafana-data:
  smartims-sonarqube-data:
  smartims-sonarqube-logs:
  smartims-sonarqube-extensions:

networks:
  smartims-network:
    driver: bridge