spring:
  config:
    import: optional:file:.env.properties

  application:
    name: smart-incident-management

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always

  logging:
    level:
      root: INFO
      com.smartims: DEBUG

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  mail:
    from: ${GMAIL_USERNAME}
    admin: ${GMAIL_PASSWORD}
  frontend:
    login-url: ${FRONTEND_LOGIN_URL:http://localhost:5173/login}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}